server:
  port: 8899
spring:
  application:
    name: Timer-Job
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    #mysql 用户名
    username: username
    #mysql密码
    password: passwrod
    #驱动名
    driver-class-name: com.mysql.jdbc.Driver
    #url
    url: jdbc:mysql://xxx?characterEncoding=UTF-8&useSSL=false
    # druid 配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 1000
      initial-size: 20
      max-wait: 5000
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
###查询日期的url
tianqiUrl: https://api.goseek.cn/Tools/holiday
pushUrl: bussinessAddress
